version: '3'
services:
  trust-authority-java-client-sgx-sample-app:
    image: trust-authority-java-client-sgx-sample-app:${TRUST_AUTHORITY_CLIENT_VERSION}
    container_name: trust-authority-java-client-sgx-sample-app
    build:
      context: ../../
      dockerfile: examples/sgx-sample-app/Dockerfile
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - MAVEN_VERSION=${MAVEN_VERSION}
        - MAVEN_PROXY_HOST=${MAVEN_PROXY_HOST}
        - MAVEN_PROXY_PORT=${MAVEN_PROXY_PORT}
        - DCAP_VERSION=${DCAP_VERSION}
        - PSW_VERSION=${PSW_VERSION}
    network_mode: "host"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    env_file:
      - ../.env
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      - /dev:/dev
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SGX_AESM_ADDR=1
