version: '3'
services:
  trust-authority-java-client-tdx-sample-app:
    image: trust-authority-java-client-tdx-sample-app:${TRUST_AUTHORITY_CLIENT_VERSION}
    container_name: trust-authority-java-client-tdx-sample-app
    build:
      context: ../../
      dockerfile: examples/tdx-sample-app/Dockerfile
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - MAVEN_VERSION=${MAVEN_VERSION}
        - MAVEN_PROXY_HOST=${MAVEN_PROXY_HOST}
        - MAVEN_PROXY_PORT=${MAVEN_PROXY_PORT}
        - DCAP_VERSION=${DCAP_VERSION}
    network_mode: "host"
    devices:
      - "/dev/tdx_guest:/dev/tdx_guest"
    env_file:
      - ../.env
    environment:
      - SPRING_PROFILES_ACTIVE=production
