version: '3'
services:
  trust-authority-java-client-sgx-sample-app:
    image: trust-authority-java-client-sgx-sample-app:${TRUST_AUTHORITY_CLIENT_VERSION}
    container_name: trust-authority-java-client-sgx-sample-app
    build:
      context: .
      dockerfile: Dockerfile.SgxSampleApp
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - MAVEN_VERSION=${MAVEN_VERSION}
        - MAVEN_PROXY_HOST=${MAVEN_PROXY_HOST}
        - MAVEN_PROXY_PORT=${MAVEN_PROXY_PORT}
        - DCAP_VERSION=${DCAP_VERSION}
        - PSW_VERSION=${PSW_VERSION}
    network_mode: "host"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    env_file:
      - .env
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      - /dev:/dev
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SGX_AESM_ADDR=1
    entrypoint: ["/app/sgx_sample_app.sh", "${TRUSTAUTHORITY_BASE_URL}", "${TRUSTAUTHORITY_API_URL}", "${TRUSTAUTHORITY_API_KEY}"]

  trust-authority-java-client-tdx-sample-app:
    image: trust-authority-java-client-tdx-sample-app:${TRUST_AUTHORITY_CLIENT_VERSION}
    container_name: trust-authority-java-client-tdx-sample-app
    build:
      context: .
      dockerfile: Dockerfile.TdxSampleApp
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - MAVEN_VERSION=${MAVEN_VERSION}
        - MAVEN_PROXY_HOST=${MAVEN_PROXY_HOST}
        - MAVEN_PROXY_PORT=${MAVEN_PROXY_PORT}
        - DCAP_VERSION=${DCAP_VERSION}
    network_mode: "host"
    devices:
      - "/dev/tdx_guest:/dev/tdx_guest"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=production
    entrypoint: ["/app/tdx_sample_app.sh", "${TRUSTAUTHORITY_BASE_URL}", "${TRUSTAUTHORITY_API_URL}", "${TRUSTAUTHORITY_API_KEY}"]
