version: '3'
services:
  trust-authority-java-client:
    image: trust-authority-java-client-image:${TRUST_AUTHORITY_CLIENT_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - MAVEN_VERSION=${MAVEN_VERSION}
        - PROXY_HOST=${PROXY_HOST}
        - PROXY_PORT=${PROXY_PORT}
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    entrypoint: ["java", "-cp", "~/.m2/repository/com/google/code/gson/gson/2.9.0/gson-2.9.0.jar:~/.m2/repository/io/jsonwebtoken/jjwt/0.12.3/jjwt-0.12.3.jar:target/trust-authority-client-java-1.0.0.jar:~/.m2/repository/io/jsonwebtoken/jjwt-impl/0.11.2/jjwt-impl-0.11.2.jar:~/.m2/repository/io/jsonwebtoken/jjwt-api/0.11.2/jjwt-api-0.11.2.jar:~/.m2/repository/io/jsonwebtoken/jjwt-jackson/0.11.2/jjwt-jackson-0.11.2.jar:~/.m2/repository/com/nimbusds/nimbus-jose-jwt/9.4/nimbus-jose-jwt-9.4.jar", "trust_authority_client.SampleApp", "${BASE_URL}", "${API_URL}", "${API_KEY}"]